using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Bennewitz.Ninja.AutoVersioning.SourceGenerators;

[SuppressMessage("ReSharper", "UnusedMember.Global")]
public static class SyntaxExtensions
{
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    public static string ToErrorString(this Diagnostic diagnostic)
    {
        if (!ReferenceEquals(diagnostic, null))
        {
            if (diagnostic.Location == Location.None) return string.Join(" | ", "global", diagnostic.GetMessage());
            return string.Join(" | ", diagnostic.Location, diagnostic.GetMessage());
        }

        return string.Empty;
    }

    public static MemberAccessExpressionSyntax MemberAccessExpression<T>(this T enumValue)
        where T : struct, Enum =>
        SyntaxFactory.MemberAccessExpression(
            SyntaxKind.SimpleMemberAccessExpression,
            SyntaxFactory.IdentifierName(typeof(T).Name),
            SyntaxFactory.IdentifierName(enumValue.ToString()));

    public static SyntaxTriviaList GeneratedCodeHeaderComment(string tool, Version version) =>
        SyntaxFactory.TriviaList(
            SyntaxFactory.Comment("//------------------------------------------------------------------------------"),
            SyntaxFactory.Comment("// <auto-generated>"),
            SyntaxFactory.Comment($"//     This code was automatically generated by {tool} version {version};"),
            SyntaxFactory.Comment("//"),
            SyntaxFactory.Comment("//     Changes to this file may cause incorrect behavior and will be lost if"),
            SyntaxFactory.Comment("//     the code is regenerated."),
            SyntaxFactory.Comment("// </auto-generated>"),
            SyntaxFactory.Comment("//------------------------------------------------------------------------------")
        );

    public static SyntaxTrivia NewLine
    {
        get
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return SyntaxFactory.CarriageReturnLineFeed;
            }

            return SyntaxFactory.LineFeed;
        }
    }

    private sealed class UsingDirectiveListBuilder
    {
        private readonly SyntaxTriviaList? _leadingTrivia;
        private readonly List<UsingDirectiveSyntax> _usingDirectiveList;
        public int Count => _usingDirectiveList.Count;

        public UsingDirectiveListBuilder(SyntaxTriviaList? leadingTrivia)
        {
            _leadingTrivia = leadingTrivia;
            _usingDirectiveList = new List<UsingDirectiveSyntax>();
        }

        public UsingDirectiveSyntax[] ToArray(SyntaxTriviaList? trailingTrivia)
        {
            if (trailingTrivia != null)
            {
                var finalList = _usingDirectiveList.ToList();
                var last = finalList.Last();
                finalList.RemoveAt(finalList.Count - 1);
                last = last.WithTrailingTrivia(trailingTrivia);
                finalList.Add(last);
                return finalList.ToArray();
            }
            return _usingDirectiveList.ToArray();
        }

        public void Add(NameSyntax name)
        {
            UsingDirectiveSyntax usingDirectiveSyntax;

            if (Count == 0 && _leadingTrivia != null)
            {
                var leadingTrivia = _leadingTrivia;
                usingDirectiveSyntax = SyntaxFactory.UsingDirective(name)
                    .WithUsingKeyword(
                        SyntaxFactory.Token(
                            leadingTrivia.Value,
                            SyntaxKind.UsingKeyword,
                            SyntaxFactory.TriviaList(
                                SyntaxFactory.Space)));
            }
            else
            {
                usingDirectiveSyntax = SyntaxFactory.UsingDirective(name);
            }

            _usingDirectiveList.Add(usingDirectiveSyntax);
        }

        public void AddRange(IEnumerable<NameSyntax> nameSyntaxEnumerable)
        {
            foreach (var usingDirectiveSyntax in nameSyntaxEnumerable)
            {
                Add(usingDirectiveSyntax);
            }
        }
    }

    public static SyntaxList<UsingDirectiveSyntax> UsingNamespaces(params string[] namespaces) =>
        UsingNamespaces(null, null, namespaces);

    public static SyntaxList<UsingDirectiveSyntax> UsingNamespaces(SyntaxTriviaList? leadingTrivia, params string[] namespaces) =>
        UsingNamespaces(leadingTrivia, null, namespaces);

    public static SyntaxList<UsingDirectiveSyntax> UsingNamespaces(
        SyntaxTriviaList? leadingTrivia,
        SyntaxTriviaList? trailingTrivia,
        params string[] namespaces)
    {
        const char delimiter = '.';

        var usingDirectiveList = new UsingDirectiveListBuilder(leadingTrivia);

        var orderedNamespaces = namespaces
            .Where(x => !string.IsNullOrEmpty(x))
            .Distinct()
            .OrderBy(x => x)
            .ToArray();

        var namespacesWithSingleIdentifier = orderedNamespaces
            .Where(x => !x.Contains(delimiter))
            .ToArray();

        if (namespacesWithSingleIdentifier.Any())
        {
            usingDirectiveList.AddRange(
                namespacesWithSingleIdentifier.Select(
                    SyntaxFactory.IdentifierName
                ));
        }

        var namespacesWithDelimiter = orderedNamespaces.Where(
            x => x.Contains(delimiter))
            .ToArray();

        if (namespacesWithDelimiter.Any())
        {
            usingDirectiveList.AddRange(namespacesWithDelimiter
                .Select(x => QualifiedName(x.Split('.'))));
        }

        return usingDirectiveList.ToArray(trailingTrivia).ToSyntaxList();
    }

    public static QualifiedNameSyntax QualifiedName(string[] nameParts)
    {
        if (nameParts.Length < 2)
        {
            throw new ArgumentException(
                $"'{nameof(nameParts)}' must contain more than 1 identifier",
                nameof(nameParts));
        }

        QualifiedNameSyntax? result = null;

        for (int i = 0; i < nameParts.Length; i++)
        {
            if (i == 0)
            {
                continue;
            }
            var currentIdentifier = SyntaxFactory.IdentifierName(nameParts[i]);
            if (result == null)
            {
                var previousIdentifier = SyntaxFactory.IdentifierName(nameParts[i - 1]);
                result = SyntaxFactory.QualifiedName(previousIdentifier, currentIdentifier);
            }
            else
            {
                result = SyntaxFactory.QualifiedName(result, currentIdentifier);
            }
        }

        return result!;
    }

    public static SyntaxList<TNode> ToSyntaxList<TNode>(this TNode node)
        where TNode : SyntaxNode =>
        ToSyntaxListImpl(new[] { node });

    public static SyntaxList<TNode> ToSyntaxList<TNode>(this IEnumerable<TNode> nodes)
        where TNode : SyntaxNode =>
        ToSyntaxListImpl(nodes.ToArray());

    [SuppressMessage("ApiDesign", "RS0030:Do not use banned APIs")]
    private static SyntaxList<TNode> ToSyntaxListImpl<TNode>(this TNode[] nodes)
        where TNode : SyntaxNode
    {
        SyntaxList<TNode> result;
        if (nodes.Length == 0)
        {
            result = SyntaxFactory.List<TNode>();
        }
        else if (nodes.Length == 1)
        {
            result = SyntaxFactory.SingletonList(nodes.First());
        }
        else
        {
            result = SyntaxFactory.List(nodes);
        }

        return result;
    }

    public static SeparatedSyntaxList<TNode> ToSeparatedSyntaxList<TNode>(this TNode node)
        where TNode : SyntaxNode =>
        ToSeparatedSyntaxListImpl(new[] { node });

    public static SeparatedSyntaxList<TNode> ToSeparatedSyntaxList<TNode>(this IEnumerable<TNode> nodes)
        where TNode : SyntaxNode =>
        ToSeparatedSyntaxListImpl(nodes.ToArray());

    [SuppressMessage("ApiDesign", "RS0030:Do not use banned APIs")]
    private static SeparatedSyntaxList<TNode> ToSeparatedSyntaxListImpl<TNode>(this TNode[] nodes)
        where TNode : SyntaxNode
    {
        SeparatedSyntaxList<TNode> result;
        if (nodes.Length == 0)
        {
            result = SyntaxFactory.SeparatedList<TNode>();
        }
        else if (nodes.Length == 1)
        {
            result = SyntaxFactory.SingletonSeparatedList(nodes.First());
        }
        else
        {
            result = SyntaxFactory.SeparatedList(nodes);
        }

        return result;
    }
}